import { translate } from '../providers/LanguageProvider';

export const apps = [
    { value: 'Airbnb', icon: 'airbnb' },
    { value: 'Amazon', icon: 'amazon' },
    { value: 'Apple', icon: 'apple' },
    { value: 'Behance', icon: 'behance' },
    { value: 'Bitbucket', icon: 'bitbucket' },
    { value: 'Chrome', icon: 'chrome' },
    { value: 'Codepen', icon: 'codepen' },
    { value: 'DeviantArt', icon: 'deviantart' },
    { value: 'Dribbble', icon: 'dribbble' },
    { value: 'Dropbox', icon: 'dropbox' },
    { value: 'Etsy', icon: 'etsy' },
    { value: 'Facebook', icon: 'facebook' },
    { value: 'Facebook Messenger', icon: 'facebook-messenger' },
    { value: 'Flickr', icon: 'flickr' },
    { value: 'Firefox', icon: 'firefox' },
    { value: 'Git', icon: 'git' },
    { value: 'GitHub', icon: 'github' },
    { value: 'GitLab', icon: 'gitlab' },
    { value: 'Goodreads', icon: 'goodreads' },
    { value: 'Google', icon: 'google' },
    { value: 'Grav', icon: 'grav' },
    { value: 'Imdb', icon: 'imdb' },
    { value: 'Instagram', icon: 'instagram' },
    { value: 'Kickstarter', icon: 'kickstarter' },
    { value: 'LinkedIn', icon: 'linkedin' },
    { value: 'Opera', icon: 'opera' },
    { value: 'Patreon', icon: 'patreon' },
    { value: 'Pinterest', icon: 'pinterest' },
    { value: 'PlayStation', icon: 'playstation' },
    { value: 'Quora', icon: 'quora' },
    { value: 'Reddit', icon: 'reddit' },
    { value: 'Safari', icon: 'safari' },
    { value: 'Salesforce', icon: 'salesforce' },
    { value: 'Shopify', icon: 'shopify' },
    { value: 'Slack', icon: 'slack' },
    { value: 'SoundCloud', icon: 'soundcloud' },
    { value: 'Spotify', icon: 'spotify' },
    { value: 'Stack Overflow', icon: 'stack-overflow' },
    { value: 'Steam', icon: 'steam' },
    { value: 'Stripe', icon: 'stripe' },
    { value: 'Telegram', icon: 'telegram' },
    { value: 'Tiktok', icon: 'tiktok' },
    { value: 'Tumblr', icon: 'tumblr' },
    { value: 'Twitch', icon: 'twitch' },
    { value: 'Twitter', icon: 'twitter' },
    { value: 'Vimeo', icon: 'vimeo' },
    { value: 'VK', icon: 'vk' },
    { value: 'WhatsApp', icon: 'whatsapp' },
    { value: 'WordPress', icon: 'wordpress' },
    { value: 'Yahoo', icon: 'yahoo' },
    { value: 'Yandex', icon: 'yandex' },
    { value: 'YouTube', icon: 'youtube' },
    { value: translate('other'), icon: 'circle-question' },
];
